### PR TITLE
Optionally render schema title and descriptions

### LINKED ISSUE #598: No description on schemas (e.g. response body schemas)
[ObjectSchema.tsx](https://github.com/Rebilly/ReDoc/blob/master/src/components/Schema/ObjectSchema.tsx) does not render schema description

### PR DESCRIPTION
**Pull request by stnguyen90**
Fixes #598, fixes #603.

### CODE REVIEW

**Comment by stnguyen90** [comment]
I can't seem to reproduce/fix the problem indicated in the build. Any help?

**Comment by RomanHotsiy** [comment]
Hi @stnguyen90. Thanks for the PR 👍 

I will review it early next week. Super busy this week.

**Comment by tomwidmer** [comment]
Should this be done by adding the options to RedocNormalizedOptions.ts and passing them through to SchemaModel? Then each component can read them out of their SchemaModel prop.

**Comment by Blacklands** [comment]
Has there been any new progress on this recently? What is missing for it to be complete?

**Comment by RomanHotsiy** [comment]
Superseded by https://github.com/Redocly/redoc/pull/1497

**Pull request closed without merging**
