### PR TITLE
Fix error with multipart/form-data

### PR DESCRIPTION
**Pull request by bautrukevich**
Related to https://github.com/Rebilly/ReDoc/issues/707

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Thanks for your PR!
I looked through it quickly and it looks good in general.

Although, I have a few concerns I want to investigate before merging this in.
If I disappear 🙈  keep pinging me, please 👉.

**Comment by bautrukevich** [comment]
@RomanGotsiy maybe you want to leave some comments? I will be glad. Because I need this feature as soon as possible. And can we release a patch with this?

**Comment by RomanGotsiy** [comment]
OK. So the first question is: why do you encode multipart/form-data as key-values pairs?

It seems to not reflect how things are encoded in reality so this is confusing.

Also, you say it is related to #707 but I look like this PR doesn't fix the issue.

> Because I need this feature as soon as possible.

If it doesn't land soon enough you can just use your fork temporary.

**Comment by bautrukevich** [comment]
@RomanGotsiy yes, you are right, this is not how it looks in browsers requests, or not looks like HTTP request, and it's simplified because we need to show somehow what developer need to send in the request.
About issue — I am using my own example and it works fine if I am setting requestBody content as multipart/form-data.
About fork — how can I use them in redoc-cli? Because redoc-cli has own package.json and do I need to use fork of redoc-cli and after one more fork for redoc? 
Thank you!

**Comment by g0ddish** [comment]
Could we get this rolled up into a release by any chance 🙈

**Comment by ClaudiaSaft** [comment]
Any update on this? or a recommended workaround/alternative ?

@bautrukevich Why did you delete your fix branch? Any specific reason?

Thanks!

**Comment by bautrukevich** [comment]
@ClaudiaSaft I don't remember exactly, maybe because it not actual anymore

**Pull request closed without merging**
