### PR TITLE
Added supporting any heading level from markdown

### PR DESCRIPTION
**Pull request by Morev1993**
@RomanHotsiy 
I have markdown documents. These have a lot of different level headings. Currently, Redoc supports only 1 and 2 level headings with anchor's links. I need more up to 6. 

## Check yourself

- [ ] Code is linted
- [ ] Tested
- [ ] All new/updated code is covered with tests

### CODE REVIEW

**Comment by Morev1993** [comment]
@RomanHotsiy take a look my solution, please

**Comment by RomanHotsiy** [comment]
Does it work? Can you share a screenshot?

**Comment by Morev1993** [comment]
@RomanHotsiy  yes
image

**Comment by Morev1993** [comment]
@RomanHotsiy  what do you think ?

**Comment by RomanHotsiy** [comment]
Hi @Morev1993, sorry for the delay.

I checked it. I'm not sure if we want to merge it. You're the only user who reported it and it adds some complexity to our codebase.

I also don't like different font sizes in the sidebar on the screenshot you sent.
Let us think a little bit and decide.

Thanks for contributing anyways 🙌

**Comment by lornajane** [comment]
Thanks again for the contribution. We decided that we aren't going to merge this pull request, so I'll close it (sorry for the slow response time, we really do appreciate you being part of the project!)

**Pull request closed without merging**
