### PR TITLE
Fix #649: correct URLs of OperationModel servers

### LINKED ISSUE #649: #opertion and #tag display in endpoint url if host is not specified
Steps to reproduce:
1. Do not specify "host" in your spec yaml/json file.
2. Open the redoc generated HTML file or host on a server.
3. Navigate doc to some endpoint to see the sample url .
good
Notice at this point, url in browser is something like "http://localhost:4300/doc/#operation/getUser"(getUser is the operationId)

4. Refresh page and check the endpoint url example
bad
"#opertion" or "#tag" is included in the url.

### PR DESCRIPTION
**Pull request by pavelzagorodnyuk**
## What/Why/How?
This PR corrects endpoint URLs (the issue #649) 

## Check yourself

- [x] Code is linted
- [x] Tested
- [x] All new/updated code is covered with tests

### CODE REVIEW

**Comment by AlexVarchuk** [comment]
@pavelzagorodnyuk Hi. Thank you for your contribution. Can you add some tests for this case?

**Comment by pavelzagorodnyuk** [comment]
Hi @AlexVarchuk! Yes, I will do it

**Comment by AlexVarchuk** [comment]
https://github.com/Redocly/redoc/issues/2090

**Review by AlexVarchuk — APPROVED** [review]

**Comment by AlexVarchuk** [comment]
@pavelzagorodnyuk Thank you a lot for your contribution. 🙌

**Comment by pavelzagorodnyuk** [comment]
Thank you too, @AlexVarchuk! Can you tell me when new version of Redoc will be released?

**Comment by AlexVarchuk** [comment]
We have a plan to do it this week.

**Pull request merged**
