### PR TITLE
fix: Fixed  method sortByRequired

### PR DESCRIPTION
**Pull request by yannan**
The method of sortByRequired has a bug, see #1104, #1121

### CODE REVIEW

**Comment by RomanHotsiy** [comment]
Hey @yannan,

The `sortByReqired` method is not obvious to read... I tried to simplify the flow and managed to get tests passing.

Could you please replace it with the following and verify you don't have an issue with openapi-cli with this version:

```ts
export function sortByRequired(fields: FieldModel[], order: string[] = []) {
  return [...fields].sort((a, b) => {
    if (!a.required && b.required) {
      return 1;
    } else if (a.required && !b.required) {
      return -1;
    } else if (a.required && b.required) {
      const aIdx = order.indexOf(a.name);
      const bIdx = order.indexOf(b.name);
      if (aIdx === -1 && bIdx !== -1) {
        return 1;
      }
      if (bIdx === -1 && aIdx !== -1) {
        return -1;
      }

      return aIdx - bIdx;
    } else {
      return 0;
    }
  });
}
```

**Comment by RomanHotsiy** [comment]
If it is, update this PR pls. I can't push to your branch

**Comment by yannan** [comment]
@RomanHotsiy. Thank you for your reply.
But We have a issue when the compareFunction(a,b) return 0 in the end of if/else condition.

If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements.the ECMAscript standard does not guarantee this behavior.

**Comment by RomanHotsiy** [comment]
I see. It is recent addition: https://v8.dev/features/stable-sort

What about this approach: https://stackoverflow.com/a/52771420/1749888?

**Comment by yannan** [comment]
Hey @RomanHotsiy.
I update this PR, please check.

**Pull request merged**
