### PR TITLE
Make redoc RTL support

### PR DESCRIPTION
**Pull request by raha1923**
This PR is related to this( #1002 ) issue and we think it's ready to merge. The functionality required for the RTL support project implemented. There are some problems, of course, so please let us know about them if you found any of them.

Notice: This PR is not contained localization.

### CODE REVIEW

**Comment by RomanHotsiy** [comment]
Thanks for your work. This is a big PR and have to be reviewed carefully.

I will review it as soon as I have time.

We plan Redoc 2.0 release soon so I will have a few days dedicated to reviewing/merging PRs soon.

**Comment by raha1923** [comment]
So good to hear that. we have done our bests to make it useful and backward compatible.

**Comment by neluzhin** [comment]
I think it's better to implement RTL and LTR support using CSS features created for that purpose (at this moment [these features have at Editor's Draft status](https://drafts.csswg.org/css-logical/), but they're [implemented in most browsers](https://caniuse.com/#feat=css-logical-props) except IE and 1st gen Edge) (but seems like `logical` keyword isn't not working in Chrome yet).

Check [MDN for docs about CSS Logical Properties and Values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).

**Comment by RomanHotsiy** [comment]
Hey @raha1923.

Are you still interested in this PR? We have it on our roadmap but we don't have enough time right now.

We're going to release 2.0.0 soon so we'll ping you here and if you are interested in this PR we would kindly ask you to rebase.

Sorry for delay.

**Comment by lornajane** [comment]
Thanks so much for opening this pull request. This isn't a feature we're comfortable adopting at this time, and the pull request is also outdated. I'm therefore closing this, but with thanks for using Redoc and sharing your ideas with us!

**Pull request closed without merging**
