### PR TITLE
fix: Handle emtpy object in security array

### PR DESCRIPTION
**Pull request by valdirmendesdev**
Fixes [#1631](https://github.com/Redocly/redoc/issues/1631)

### CODE REVIEW

**Comment by RomanHotsiy** [comment]
This looks good! Thanks @valdirmendesdev 

I'm just not 100% sure on `Anonymous` term.

@cmeeren what do you think?

**Comment by ian-zunderdorp** [comment]
If I can offer a suggestion: How about "Not applicable"?

**Comment by cmeeren** [comment]
As demonstrated in the issue, it has to work together with authorization. So "Not applicable" won't work. I suggest "No authorization". Works in combination with another auth scheme, and describes exactly what it is.

**Comment by cmeeren** [comment]
"None" could also work. That would avoid the awkward issue that is "authorization" vs. "authentication". The standard HTTP header is "Authorization", but it is a misnomer; the correct term is "Authentication". (Though ReDoc already displays this as "Authorization", so I'm not sure how much it matters.)

**Comment by valdirmendesdev** [comment]
@cmeeren how about "not required"?!

**Comment by RomanHotsiy** [comment]
All good suggestions here!

cc @adamaltman

**Comment by cmeeren** [comment]
"Not required" could also work. Personally I would prefer "None", but not by much.

**Review by adamaltman — COMMENTED** [review]
This is a good idea. 🎉 🥳 

In reference docs 2.0 (our premium product) we changed the name from "Authorization" to "Security". Why? Because security is in line with the name in the OpenAPI spec and can describe both authentication and authorization (what scopes are required for access). I think "None" still makes sense if that label changed to "Security" here as well.

One additional point, how about adding a test to prove it works and prevent regressions?

**Comment by valdirmendesdev** [comment]
@adamaltman thanks for your suggestion. I will think how to test this behavior. Maybe rendering and testing the text of the result, what do you think?

**Comment by RomanHotsiy** [comment]
@valdirmendesdev yes! You can use shallow render: https://github.com/Redocly/redoc/blob/master/src/components/__tests__/OneOfSchema.test.tsx#L34

**Comment by valdirmendesdev** [comment]
@adamaltman I tried to write unit test to cover the expected behavior. Can you check if I am in the right way, please?

**Comment by RomanHotsiy** [comment]
@valdirmendesdev that's great!

**Review by RomanHotsiy — APPROVED** [review]

**Comment by RomanHotsiy** [comment]
Let me know if you're ready to merge or if you wanted to add anything else.

**Comment by valdirmendesdev** [comment]
Thanks @RomanHotsiy, for now, I will not add anything else.

**Review by AlexVarchuk — APPROVED** [review]

**Pull request merged**
