### PR TITLE
fix: display response code at the top after adding a line break

### LINKED ISSUE #1371: Redoc doesn't display error code at the top after adding a line break
After adding a couple of line breaks in the description of an API response. Weirdly, Redoc shows the error code at the bottom of the description section:
image

I believe its a bug in Redoc because in swagger UI the line breaks are inserted and the UI looks good:

Screen Shot 2020-09-01 at 19 47 33

This json snippet got generated by my application which is uses OpenAPI v3 specs for generating the schema
```json
  "responses": {
    "500": {
      "description": "Erreur de serveur interne, rien ne peut être fait à ce sujet.  <br/><br/>codes d'erreur possibles: <br/>internal.server.error = erreur interne du serveur",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ErrorBody"
          }
        }
      }
    },
    "200": {
      "description": "OK",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CityRepositoryRepresentation"
          }
        }
      }
    }
  }
```

Am I missing something? Any help would be much appreciated.

### PR DESCRIPTION
**Pull request by stasiukanya**
Fixes #1371

### CODE REVIEW

**Review by RomanHotsiy — APPROVED** [review]

**Comment by Hamzablm** [comment]
Thank you so so much for fixing it 👏

**Comment by Hamzablm** [comment]
I believe that the bug isn't fully resolved yet. It's fixed only for the small screen width. 

When I widen the browser window. Response code doesn't show up correctly in the UI:

image

**Comment by stasiukanya** [comment]
@Hamzablm The new version was not yet published. I will land into the next release.

**Comment by Hamzablm** [comment]
Hello @stasiukanya. I hope you're well. 
I just pulled the latest redoc image from docker hub, and I've run it with our OpenAPI specs. The issue still persists, however. I believe it is deployed. Isn't it?

**Comment by RomanHotsiy** [comment]
@Hamzablm this has been released in rc.41. Maybe the docker hub is behind. We'll check it out later this week.

**Comment by Hamzablm** [comment]
@RomanHotsiy Is it released in the docker hub? How can I know that? Please, we really need this bug to be fixed.

**Comment by Hamzablm** [comment]
Hello, @RomanHotsiy @stasiukanya. I hope you're well guys. I want to let you know that I just pulled the latest code from the master branch. I've built the image and run it but the issue still persists. I believe the bug isn't fixed. 
Have you guys tested it on a large widescreen? Because I tested it on a 27-inch (5120 x 2880) monitor and it's not working as expected. Though, it's working on my MacBook.

**Pull request merged**
