### PR TITLE
fix: lazy fields to prevent crash on complex nested oneOf's

### LINKED ISSUE #696: Schema causing ReDoc to run out of memory
We have a rather large schema that is causing Redoc to fail to render as the browser runs out of memory.

I have tried utilising redoc-cli to bundle but this will run seemingly forever and never complete.

The schema can be found here: https://gist.github.com/AlexRichter/001f64d9c5ac17a8a0bfdb1a771eef71

I have tried creating a minimal use case but can't as I believe the issue is due to the complexity of the schema.

You can fix it by removing some of the `oneOf` and `discriminator` in `CheckResource`. If you only have 3 it will render quickly, up to 5 and it takes ~18 seconds. All of them and it will never complete.

Your help is much appreciated!

### PR DESCRIPTION
**Pull request by RomanHotsiy**
Fixes #696

### CODE REVIEW

**Comment by jfoliveira** [comment]
Hey @knidarkness @okachynskyy as this seems to fix #696 #1176 #1397 and #1417 could you please review?
Just a heads up as you guys are the only ones marked as reviewers.

**Comment by BobbyJohansen** [comment]
Any Movement on this? We have some pretty large specs that we need to churn through

**Comment by glen-84** [comment]
I tried this with our spec which is ~28,000 lines, and:

1. `serve` uses up all available memory.
2. `bundle` hits a `RangeError: Invalid string length` at objectToHTML (.../redoc.lib.js:11543:19).

😞

**Comment by prabhutw** [comment]
@RomanHotsiy When can we expect this PR to be merged? We are also facing performance issue because of oneOf
This PR will fix #1814 as well

**Comment by RomanHotsiy** [comment]
This PR is not ready to merge, unfortunately. It causes many side effects across the app state so we have to come up with a better solution.

**Pull request closed without merging**
