### PR TITLE
[FEATURE] Collapsible Groups

### PR DESCRIPTION
**Pull request by bradennapier**
So I needed this so I figured I'd try my hand at contributing to the repo!  I put some time into thinking out the various potential cases to try to make the UX intuitive here.

1. `x-tagGroups` can have a setting `collapsible: true` which will make them a collapsible group.
2. Retains general scroll-through behavior (auto-expand as user scrolls, etc).
3. Allows closing / collapsing of a group by clicking on an open group.  
  - This will scroll to the first element of the group, scrolling down will then re-open the group naturally.
4. Collapsible groups default to `collapsed` unless you are viewing a subitem of the group or click the item.
5. Adds a property `collapsible` to tag items which defaults to `true`.  Uses this value along with `items.length` to determine if it is collapsible.
6. Adds margin to each level rendered (clearly collapsible -> tag -> operations has reduced width available).
7.  I would note that running prettier seems to have adjusted some other files that I did not touch in this PR.  It would seem it wasn't run on a previous PR or commit.  Just an FYI there.  
  - For easier diffing, [omitting whitespace may be best](https://github.com/Rebilly/ReDoc/pull/853/files?w=1)

---

### Resolves:

#826 

---

### Spec Example

```yaml
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
  - name: SubItem One
    description: |
      SubItem One Description!
  - name: SubItem Two
    description: |
      SubItem Two Description!
x-tagGroups:
  - name: General
    collapsible: true
    tags:
      - pet
      - store
  - name: User Management
    tags:
      - user
  - name: Collapsible Group
    collapsible: true
    tags:
      - SubItem One
      - SubItem Two
```
---

### To Do:

- [x] Currently collapsing a 2-level collapsible will navigate to the element above it if collapsed and it isn't a top-level item.  Need to fix this.  

> General > [pet, store] -- When store is expanded and you collapse it at the moment it will scroll to the top of pet rather than the top of store.  Will fix this shortly.

- [ ] Was not sure if the `menu.collapse()` needed to be decorated with `@action` as I am not familiar with `mobx` and it does work fine without it.  If it is needed, prob easiest to just use the github suggestions feature and add it inline here so we can commit quickly once approved :-) 

- [x] **NOT PLANNED** - Technically operations do not add the proper margin to them so the method tag is rendered a bit too far to the left.  I did this on purpose to preserve space since it does not seem to look that bad.  Easy enough to provide if desired though.

- [x] **NOT IN SCOPE** - related to the above, for truly recursive handling of tags in this manner, we would need to do a more powerful search to find the best element to scroll to in this case.  It does not seem necessary as it is unlikely that supporting more than 2-levels will make sense at any point (or even be possible).  Honestly only real use-case I see for this is for better organizing of what would otherwise be top-level tags.

---

### Side Notes

- I noticed that if you happen to render the same tag in multiple groups it will break.  While in many cases this probably will never happen - a few things should probably be considered here (out of scope and not planning to submit PR for this one, just noting it while I am typing :-D):
  1. Groups should be rendered as top-level heading encapsulating its child items (perhaps optional via setting).  
      - This would also simplify scroll behavior since we do not need to try to determine best place to scroll to when a group is actually clicked.
  2. History should include the general breadcrumbs if possible for differentiating values.

---

### Screenshots

image

image

image

Also supports mixed collapsible/static:

image

### CODE REVIEW

**Comment by bradennapier** [comment]
Tests are failing but it does not appear to be due to my changes here as others are seeing same.  I can't imagine this would cause tests to fail but possible ofc!

**Comment by bradennapier** [comment]
Just shipped our documentation over at IDEX with this PR, https://docs.idex.market/  for reference

**Comment by mikouaj** [comment]
+1
feature is useful when creating API catalog for bigger platforms

**Comment by ngthtung** [comment]
+1

**Comment by CarltonHowell** [comment]
@bradennapier Any chance this gets merged in production? Would love this feature!

**Comment by bradennapier** [comment]
The team never even responded to it so I don't think they are really open to ideas or public contribution.  

At this point this PR is likely so out of date it'd need to be redone. 

We use the PR ourselves directly at https://docs.idex.market but for our next gen docs are switching to even more custom options such as docosaurus or gatsby, unfortunately.

**Comment by RomanHotsiy** [comment]
@bradennapier sorry, we didn't have enough resources.

This is actually out of scope of this project. We try to keep it simple.

**Pull request closed without merging**
