### PR TITLE
Prefix operation ids with parent id

### PR DESCRIPTION
**Pull request by BBlowers**
Currently, operations that have multiple tags appear multiple times on the page as desired, however, their containing elements share the same id. This means when using the side menu to navigate the user is always taken to the earliest occurrence.

To demonstrate I've added the `pet` tag to the "Returns pet inventories by status" operation in this gif. Clicking on the "Returns pet inventories by status" operation in the store section takes the user to the operation under the pet section
redoc section links

A solution to this is to prefix operation ids with their parent's id.

### CODE REVIEW

**Comment by RomanHotsiy** [comment]
@BBlowers thank you for your PR! Unfortunately, this is a breaking change. Old URLs will stop working.

Would you have some time add support for old `operation/*` URLs or to enable this behavior optionally by creating new Redoc option.

Let me know, I can pick this up.

**Comment by BBlowers** [comment]
@RomanHotsiy good point.

Supporting both `operation/*` and `parent/*/operation*` makes the most sense to me. I'll update the PR asap

**Comment by BBlowers** [comment]
@RomanHotsiy I've added the `operation/*` format id to the OperationRow component. 

I've kept the changes to a minimum as I'm not too familiar with typescript.

**Comment by BBlowers** [comment]
@RomanHotsiy is this PR likely to get another look soon?

**Comment by RomanHotsiy** [comment]
Hey @BBlowers,

Sorry for the radio silence. I will review and merge it this week. This looks good. I just have to test if it doesn't break our other tools.

**Comment by BBlowers** [comment]
@RomanHotsiy How did the tests go? Is this okay to be merged?

**Comment by RomanHotsiy** [comment]
Oh, sorry, not really. I haven't tested it yet.

Thanks for pinging. I am now adding it to the team sprint board so we prioritize it. If it is not merged mid-next week - feel free to ping me again!

Sorry, busy months for me :(

**Comment by RomanHotsiy** [comment]
I just tested it out and there is some conflict with our internal tool. It should be fixed early next week and I will merge after.

**Comment by BBlowers** [comment]
any news?

**Comment by asauray** [comment]
@RomanHotsiy Any update on this pr?

**Comment by hefekranz** [comment]
still a major issue. Any updates?

**Comment by altanozlu** [comment]
any news ?

**Comment by anastasiia-developer** [comment]
@BBlowers  Hi! Thank you for your contribution to redoc.

**Pull request merged**
