### PR TITLE
add classNames to various places to allow for more control of styling

### PR DESCRIPTION
**Pull request by edrdoprz**
Applying styling changes using the theming capability of ReDoc works great, but sometimes you need a bit more control.

The classNames I have added are not comprehensive, but it provides a few more anchor points for users to more precisely style their docs.

Would love to get feedback from the ReDoc team and/or others!

### CODE REVIEW

**Comment by calebcase** [comment]
@RomanGotsiy Is this suitable to be merged?

**Comment by devilcoders** [comment]
Is there any chances this will be merged any time soon?

**Comment by RomanHotsiy** [comment]
Hey here! Terribly sorry for the huge delay.

We're not sure if this should be merged.
This will make future changes in CSS harder as it will break any custom styling.

I will review this PR again in early Feb as I'm super busy now.

**Comment by AlexVarchuk** [comment]
@edrdoprz Hi! Thanks for contributing. 
We can't merge it. Because it makes CSS changes harder. 🙈

In the future, maybe we implement CSS variables for better customization.

**Pull request closed without merging**
