### PR TITLE
add support for subtitles in the tags description

### PR DESCRIPTION
**Pull request by ingoclaro**
Add support for titles in tags so that they show up in the navigation menu.

redoc_interactive_demo_and_app_js_ ___sites_github_groupondev_com_ingo_3pip-swagger2

### CODE REVIEW

**Comment by ingoclaro** [comment]
getting this error:
```
Opening Cypress...
You passed the --record flag but did not provide us your Record Key.
You can pass us your Record Key like this:
  cypress run --record --key <record_key>
You can also set the key as an environment variable with the name CYPRESS_RECORD_KEY.
https://on.cypress.io/how-do-i-record-runs
```

**Comment by RomanGotsiy** [comment]
@ingoclaro nice!!!
I will check this out ASAP

**Comment by ingoclaro** [comment]
is there anything I can do with this? It seems that the build fails on PR for lack of config settings of CI for the PR case...

**Comment by RomanGotsiy** [comment]
@ingoclaro yes, don't worry about failing the build.
I just didn't have time to review it carefully yet. I will review it later today!

**Comment by RomanGotsiy** [comment]
@ingoclaro I checked it out! LGTM. I just pushed one small fix for correct depth calculation.
But I am not happy on how spacing looks like. Give me one more day to figure out how to make it better

Thanks for your work! I will merge it and release till the end of the week!

**Comment by ingoclaro** [comment]
great, thanks!

**Comment by ingoclaro** [comment]
@RomanGotsiy hi, do you need any help with this feature?

**Comment by RomanGotsiy** [comment]
@ingoclaro still haven't had time to come up with proper item spacing.
But this will be definitely merged!

**Pull request closed without merging**
