### PR TITLE
Tags side menu with markdown and object description

### PR DESCRIPTION
**Pull request by nanov**
Pretty quick workaround to be able to add additional side menu sections to tags, in the same manner it is done in the info description object.

Also an <object-description> component was added which prints a referenced object/schema, and optionally a referenced example.

Combining both one may achieve similar structure to the one [Stripe](https://stripe.com/docs/api) uses for their own documentation.

### CODE REVIEW

**Comment by cmeeren** [comment]
Brilliant! Would love for this to get merged. But could it make more sense to use e.g. `x-object-description`, which could be a supported key in a Tag object and other relevant places?

**Comment by nanov** [comment]
The ```object-description``` tag is a pseudo html tag, it is used inside markdown descriptions, similar to the way ```security-definitions``` tag is being used.

That is why it not prefixed with an ```x-```.

Additionally, sub-menus are created out of markdown headings so you could create richer endpoint menus with additional info beside endpoints.

Frankly, I don't know if tags are rendered if there are no endpoints inside them, but that should be an easy fix.

I am open to suggestions proposals n how to make this more useful.

**Comment by cmeeren** [comment]
Can you give an example of how the tag/object is rendered?

**Comment by nanov** [comment]
You could [clone this branch](https://github.com/eCollect/ReDoc/tree/tags-side-menu-and-object-description) and run the demo.

They render as the same way as responses, not unlike what stripe does. :)

**Comment by cmeeren** [comment]
Sorry, I'm not proficient in JS development. I have node installed, but I have no idea how to run the demo. If it's just a matter of running a few commands, could you give me the commands to run?

**Comment by nanov** [comment]
Sure, here is a step-by-step guide :

```sh
# clone ( my fork ) repository
git clone https://github.com/eCollect/ReDoc
# change to repository directory
cd ReDoc
# switch to this feature branch
git checkout tags-side-menu-and-object-description
# in case you don't have it, install yarn globally
npm i -g yarn
# install project dependencies - might take a minute or so
yarn install
# run the demo - might take a minute or so
yarn run start
```
Then you open your browser at http://localhost:9090.

Under Pet and Store you could see submenus "The Pet Object" and "The Store Object", this is more or less it.

I know notice an annoying spacing issue on the menu side which should be fixed, but the idea is pretty much the same.

**Comment by cmeeren** [comment]
I get an error on `yarn install`:

```
C:\GH\ReDoc>yarn install
yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error webpack@4.18.1: The engine "node" is incompatible with this module. Expected version ">=6.11.5". Got "6.10.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by nanov** [comment]
Ah, Windows... :/

I guess you have an old node version. I am not sure about how one may update his node on windows ( just downloading binaries ? ), an update ( and reopening terminal ) should do it.

**Comment by RomanGotsiy** [comment]
Sorry for not looking into this. Super busy recent days 🙀
Will get to this as soon as find some time.

**Comment by cmeeren** [comment]
Other build problems occurred. Likely nothing that can't easily be fixed, but I'll pass on the demo from this PR as it's only to satisfy my curiosity.

I'm super looking forward to this being implemented in some form or another; I can probably shave my yaml files in half since I currently have duplicated the schema definitions as manual markdown tables in the tag descriptions.

**Comment by nanov** [comment]
I've deployed an [online demo](https://ecollect.github.io/ReDoc/index.html).

**Comment by cmeeren** [comment]
Wow, thanks! It looks very good. Does it also render the object description, if any?

**Comment by cmeeren** [comment]
Also, what does it do regarding properties that are read-only and write-only? I suggest it should show both (since they're part of the object and it's rendered outside any request/response context), but that the members should be marked read-only or write-only.

**Comment by nanov** [comment]
To answer your both questions.

**Does it also render the object description, if any?**

As it is injected with markdown, you could write any description you wish ( actually rendering the root object description might be an idea, need to take a look ).

**What does it do regarding properties that are read-only and write-only?**

It renders the same thing, as if this schema is used in response, this means it is omitting write-only options ( a those are, normally, a prat of the request, not the model ).
One thing i wanted to add is to now show the ```required``` caption. It is not a problem to expose both options to the component so the user may decide what to render depending on his use-case.

**Comment by cmeeren** [comment]
Thanks. I suggest allowing the user to render both read-only and write-only properties, if desired. I need that for my use-case. As you say, normally that property would be part of a request and not a model, but there are exceptions, such as when following the [JSON-API](https://jsonapi.org/) standard which is fairly strict about everything needing to be part of a resource. A good example of a write-only property is a `password` field on a `user` resource. It's conceptually part of the resource and should be listed as a property that can be used, but it will of course never be returned in responses.

(One could argue exactly how to represent password changes in an API and how the choice of JSON-API vs. another standard influences that; that is besides the point here. I'm just saying there are valid use-cases requiring write-only properties as part of the conceptual model, which should be shown in the model rendering.)

Furthermore, I strongly suggest that read-only and write-only properties are marked in some way, e.g. in the same way as `required`. (For example, `required, read-only` could be shown beneath the name of a property marked with `readOnly: true` and `required: true`).

**Comment by nanov** [comment]
So I have added showReadOnly and showWriteOnly options ( the default is to show readOnly and not to show writeOnly ).
I will add labels to those as soon as i find the time.

**Comment by cmeeren** [comment]
Brilliant, thanks! Really looking forward to this 😊

**Comment by viralanomaly** [comment]
The ability to print an object would be amazingly useful to me.  Hopefully @RomanGotsiy can get to it soon!

**Comment by nanov** [comment]
Technically it is not a problem to implement this, the question which exact "objects" ( ie. schemas ) should the tag render. As the "components/schemas" section contains all the schemas ( including ones that are only referenced by others but not used directly, or even unused ones ), the list of the schemas is really specific. Additionally you may want those schemas in a certain order, which again needs to be setup somehow.

I think it is a lot easier, and makes more sense, to get this generated programmatically on side that generates the specification, or be done manually.

**Comment by cmeeren** [comment]
Aside from the assumedly trivial `yarn.lock` conflict, are there any outstanding issues here, or can it be merged? There's a lot of people eagerly awaiting this (#134)! 😁

**Comment by cmeeren** [comment]
@RomanGotsiy Is this waiting for anything in particular?

**Comment by Jarema** [comment]
@RomanGotsiy any change of merging this soon?
Lot of people waits for it, me including :). Actually, I need it so much I'm considering using fork.

**Comment by RomanGotsiy** [comment]
@Jarema @cmeeren @nanov 	

Sorry for the delay. I am a bit busy right now and this PR needs careful reviewing.
I will get to this ASAP (hopefully till the end of Jan).

Thanks for pinging me here! If I don't review it till the end of Jan ping me again, please 🤜

**Comment by nanov** [comment]
@tomq42 Could you explain you idea more in detail, as I am not really sure I get it.

My idea was to leave it as free as possible in order to give the user ( ie. schema owner ) the freedom to structure his documentation as needed.

**Comment by tomq42** [comment]
@nanov What I had looked for when I didn't realise I could do this to start with, was the ability to just put a tag on a schema. So the normal "operations" part of the output is built by listing the paths and method to get the operations, and then matching the "tag" values on each of those  with the tags definition list (don't know which way round it goes, but my guess is it lists through /tags, then for each one lists through /paths and the contained operations and renders any that have a matching tag in their tags array).

What I naively tried was to do exactly the same, but put a tag on a schema in /components/schemas. However, the OpenAPI spec doesn't allow tag on a schema, but does allow extensions, so you could use a custom extension "x-schema-tag" or whatever. This seems to most closely follow the way that the operations are rendered.

My guess is that within each tag section it would render operations first, then render schemas. It would just list through /components/schemas in the same way it lists through /paths, and render the schemas that are tagged with the current tag in the same way it renders the operations tagged with the current tag.  I can then choose to create a tag for just schemas, or I can mix then with the relevant operations.

**Comment by cmeeren** [comment]
I am more in favor of the existing approach in this PR, which allows placing a tag exactly where one wants it in any description (e.g. in a tag description).

**Comment by tomq42** [comment]
I suppose my argument is that if you were to that, then you may as well replace the automatic rendering of paths too with a custom html tag, and indeed essentially everything else with custom html tags, so you basically end up with a completely custom facility that you can build whatever documentation format you want. 

I can see the attraction of a custom html tag sure. It's just it's inconsistent with the way that paths are done, that's all. 
Note that they aren't actually exclusive. No reason why they couldn't both exist. I haven't had a chance to try and get my mind around how the code works, otherwise I'd give it a go.

**Comment by nanov** [comment]
That was actually my first implantation ( still used internally on some documentations ).

When it got to the point that I wanted to do a "one-size-fits-all" PR/feature, bearing in mind that this is anyways not strictly standard, I have decided to go this way because of the flexibility it allows ( menu order, before/after descriptions and more ).

I am not saying this is the best solutions, I am just explaining the thought behind the chosen way. I am more than open to suggestions in order to make this as complete as possible.

**Comment by tomq42** [comment]
I'm really struggling to get an environment where I can test this out. I'm not that much of an npm expert. The main problem is I'm wanting to render the docs offline using redoc-cli, but I'm struggling to work out how to get an environment in which I can do that.

**Comment by nanov** [comment]
Well, you can either clone [my fork](https://github.com/eCollect/ReDoc) and then test it ( without redoc-cli ), or look at the deployed [online example](https://ecollect.github.io/ReDoc/).

Bear in mind that the fork is based on an old ReDoc version.

I could publish a "unofficial" fork of both redoc and redoc-cli with the updated features, the problem is maintaining it, as this is by far not my main focus.

I believe that once Roman will give it a look we could merge it ( with some possible mainly styling tweaks ) in the main project, otherwise i would need to think about another way to structure the feature  ( code/file-wise ), so that maintaining a fork would be more straight forward.

**Comment by tomq42** [comment]
@nanov I need to get to a point I can run this on my own openapi spec within my own build, which relies on static rendering of the doc using redoc-cli. At the moment I can't work out how to bundle and publish it to our own internal npm repository so I can consume it. I get loads of compile errors out of "npm run bundle". It's all extremely frustrating. My experience of development in such environments isn't great, so I've no idea whether that's all to be expected or not. It doesn't feel like it should be. I've already fixed up a number of compile errors in the cli code to get that to build. as I need a new version of that in order to reference the different version of redoc I'll need to use. But redoc itself is proving harder to deal with.

**Comment by wyau7** [comment]
@RomanGotsiy By any chance, did you have a chance to review this? I'm interested in getting this feature as well and would prefer being able to refer to the redoc.standalone.js other than just being able to test it out with the demo. Is there a way to generate a bundled js file with @nanov's changes?

**Comment by wyau7** [comment]
> @RomanGotsiy By any chance, did you have a chance to review this? I'm interested in getting this feature as well and would prefer being able to refer to the redoc.standalone.js other than just being able to test it out with the demo. Is there a way to generate a bundled js file with @nanov's changes?

Never mind - I figured out how to reference the changes made in this PR. My only question now is when will the PR be merged.

**Comment by BenAlderfer** [comment]
@nanov can you give an example of how to add object-descriptions to the spec for use with the cli? When I tried to modify my spec like `demo/openapi.yaml` and passed it to the cli, it just outputs either the react component as a string or nothing at all (note - I'm not very familiar with react). Even using the exact `.yaml` in your pr with the cli, I'm seeing the headers but no content in the models section

Here's what it looks like: 
Screen Shot 2019-03-08 at 2 26 17 PM

**Comment by nanov** [comment]
I am really not sure about how to use it with the cli, maybe @wyau7 can give you some hints.

If nothing comes up until monday, I'll take a look once in the office.

**Comment by BenAlderfer** [comment]
@nanov were you able to make any progress on this? I haven't gotten mine to work yet

**Comment by BenAlderfer** [comment]
@wyau7 how were you able to run it locally? I've tried a number of things and I keep hitting roadblocks

**Comment by wyau7** [comment]
@BenAlderfer After I download the project, I generated a JS file that I reference in my code.

In my case, I am using Docker, so I have a start script (Dockerfile) that looks something like this to generate the file:

RUN git clone https://github.com/eCollect/ReDoc.git
WORKDIR ReDoc
RUN git checkout tags-side-menu-and-object-description
RUN yarn install --frozen-lockfile --ignore-optional --ignore-scripts
RUN npm run bundle:standalone #this generates the JS file
RUN cp bundles/redoc.standalone.js /usr/share/nginx/html/redoc.standalone.js

Let me know if you have any question. This may not be the best way to do it, but that's all I have for now.

**Comment by magnayn** [comment]
Passing through wanting this feature...

**Comment by BenAlderfer** [comment]
I did try the same approach of generating the standalone js file and using that with the static page hitting the spec endpoint, but I wasn't able to get it working. Not sure if its an issue with my formatting or the fact that its converting from swagger (2.0) spec

**Comment by wyau7** [comment]
didn't realize you were using swagger 2.0; I also had to tag things in a very specific way (like the way the demo is set up) to get it to work.

**Comment by BenAlderfer** [comment]
@RomanGotsiy could you take a look at this?

**Comment by cmeeren** [comment]
Now that the merge conflicts have been fixed, it would be fantastic if you could take a look at this @RomanGotsiy! <3 🚀

**Comment by cmeeren** [comment]
@RomanGotsiy pretty pretty please have a look at this? :) I'm on the verge of using a fork, which I really don't want to (technical complexities as well as community splitting).

**Comment by RomanGotsiy** [comment]
Sorry for the delay. I'm super busy.

I will try my best to check this out and merge on weekends.

**Comment by RomanGotsiy** [comment]
Sorry folks, I still haven't had a chance to take a look at this :

I'm merging simple PR's but this one requires a careful look. ReDoc is now used in a bunch of contexts so I need to make sure it fits all of them.

The main reason why I am delaying this is I now have mixed filings about how the `security-definitions` tag works... I am thinking about some alternatives. I feel uncomfortable with the current implementation.

Sorry again for the huge delay and thanks for your contributions 🙏!
I will keep you updated!

**Comment by lagonnebula** [comment]
Hello @nanov !
I pulled your fork, and tried the Side menu, it work pretty nice, but when I bundkle it in one static file with the CLI, this doesn't work.  (It keep the <object-description> tag).

And some basic fallback, you mispelled OBJECT_DEFINTION_COMPONENT_NAME, you forgot an I in definition.

**Comment by nanov** [comment]
@lagonnebula Hi,

Thank for the typo tip!

Bundeling with the current PR won't work because the cli uses the npm version of redoc, which does not include tis PR.

One thing that can be done is to publish a temporary fork of both in order to make those bundelabale, or alternatively to play with bundler code to make it use the source version ( what we did internally ).

**Comment by Vanclief** [comment]
@RomanHotsiy hey man, I hope you have a chance to look this soon, would be an awesome addition.

**Comment by nanov** [comment]
@RomanHotsiy let me know if you need any assistance ;)

**Comment by RomanHotsiy** [comment]
@nanov I am thinking about renaming the component. `ObjectDescription` is not precise. I can confuse it with markdown description. Also, word `Object` is not how everyone calls schemas. What do you think about the following ideas:

- `ModelDetails`
- just `Model`
- `SchemaInfo`
- `SchemaDetails`
- `SchemaDefinition`
- just `Schema`

??

Personally, I prefer `SchemaDefinition`.

**Comment by nanov** [comment]
In my opinion it should definitely be something with ```Schema```.

I would say ```Schema``` is too generic ( in case we'll want to add something else in the future ), so I'll stick to ```SchemaDefinition```.

**Comment by RomanHotsiy** [comment]
Great job @nanov! Sorry for so huuuge delay!

**Comment by cmeeren** [comment]
Will you add a note to the readme also on how it can be used?

**Comment by RomanHotsiy** [comment]
Accidentally released it with wrong component name in rc.11 🙈

Fixed it in `rc.12`.

I will add docs later. Although, PR with README docs would be appreciated 🙏

**Comment by cmeeren** [comment]
@nanov Could you just briefly describe basic usage?

**Comment by nanov** [comment]
Sure!

We could basically split it into two parts.

## Adding submenus inside tag descriptions

One could build richer menus by adding (markdown) headings into tag descriptions. Basically it's the same functionality as in the main ```info.description``` property only that those menu sections will be available as submenus of the main tag menu section.

### Example usage:

```yaml
  - name: store_model
    x-displayName: The Order Object
    description: |
      The order objects contains all the needed information about your orders
      ## Late Orders
      Late orders are marked with a dedicated flag
```

## Injecting Schema Definitions

The ability to inject desired schema (model/object) definitions into tag descriptions trough a dedicated ```SchemaDefinition``` tag.

The tag accepts the following properties :

| name | required | type | description | example
| ----- | :----: | --- | --------- | -- |
| schemaRef | * | string (json-pointer) | a pointer to the desired schema | #/components/schemas/Pet |
| exampleRef |   | string / (json-pointer) | optional pointer to a desired example | #/components/examples/Order |
| showReadOnly |   | boolean | weather to show read-only properties ( defaults to true ) | {false} |
| showWriteOnly |   | boolean | weather to show write-only properties ( defaults to false ) | {true} |

### Example usage:

#### minimal:
```<SchemaDefinition schemaRef="#/components/schemas/Pet" />```

#### full 
```<SchemaDefinition schemaRef="#/components/schemas/Order" exampleRef="#/components/examples/Order" showReadOnly={true} showWriteOnly={true} />```

**Comment by cmeeren** [comment]
Thanks, it's working great! Would it be possible to add an option for auto-expanding child objects to some desired level? Even just one level would work great for e.g. JSON-API resources, since then the attribute, relationships, and links would be visible and searchable by Ctrl-F (I know our API client devs use that to find stuff in the docs).

**Comment by nanov** [comment]
I am afraid this is out of the scope of this ( already merged ) PR, but I think you'll find a solution [here](https://github.com/Redocly/redoc/issues/211).

**Comment by wyau7** [comment]
@RomanHotsiy , @nanov - I'm not sure if this is addressed anywhere, but schemas with an external reference in allOf are not displaying (they show up blank). Can you let me know who I need to talk to on this? Thanks!

**Comment by nanov** [comment]
@wyau7 could you post your schema, or in ideally a repro.

**Comment by wyau7** [comment]
@nanov - here's an example schema (located in a file called producer.yaml):

`Producer:
      allOf:
        - $ref: 'admin.yaml#/components/schemas/Admin'
        - properties:
            title:
              type: string`

**Comment by nanov** [comment]
could you share your full schema?

**Comment by wyau7** [comment]
```
(producer.yaml)
Producer:
      allOf:
        - $ref: 'admin.yaml#/components/schemas/Admin'
        - properties:
            title:
              type: string

(admin.yaml)
Admin:
      required: [type,name,emailAddress]
      properties:
        id:
          type: integer
          readOnly: true
        type:
          description: readOnly after initial creation of Admin (AccountAdmin or Producer) resource
          type: string
          enum: [ACCOUNT,PRODUCER]
        name:
          $ref: 'shared.yaml#/components/schemas/Name'
        emailAddress:
          type: string

(shared.yaml)
Name:
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
```

**Comment by wyau7** [comment]
@nanov - let me know if you need more information - thanks!

**Comment by HughKu** [comment]
Thanks. Is there any way of doing this by inputting JSON instead of YAML?

**Comment by Blacklands** [comment]
I noticed that the description of the schema object itself (the description on the root level) is not rendered when using the `<SchemaDefinition [...]>` tag.

Would it be possible to add this? If I (as a user) am looking at the existing schemas in the API, I would also want to see the descriptions for them.

Right now, as a workaround, I am copy-pasting the description in question next to the `<SchemaDefinition [...]>` tag - but this is additional work and also error-prone.

Maybe another option for the tag could be added for this? Something like `<SchemaDefinition [...] showRootDesc={true}|{false}`.

**Comment by RomanHotsiy** [comment]
@Blacklands this is tracked in https://github.com/Redocly/redoc/issues/720

**Comment by Blacklands** [comment]
@RomanHotsiy Apologies, I completely missed this issue. I even checked for other issues about this but I managed to overlook this one. Thank you!

**Comment by damianobarbati** [comment]
What is the current intended way to display models in generated docs without using React component?

**Comment by osamaramihafez** [comment]
Is there an example of how this can be used with in json? Really new to redoc, but I'd love to have this feature added to a project.

**Comment by fsargent** [comment]
@osamaramihafez 
> Is there an example of how this can be used with a json schema? Really new to redoc, but I'd love to have this feature added to a project. (never mind I just took the petstore example yaml file and converted it to json. You can see how it's used that way).

I had the exact same issue, and I've cracked it. You need to escape the quotes with `\`. 
So in top level tags:

```{
	"name": "create-verification-request",
"x-displayName": "Verification Request Schema",
"description": "<SchemaDefinition schemaRef=\"#/components/schemas/create-verification-request\" />"
,```

**Pull request merged**
