### PR TITLE
Document theme options

### PR DESCRIPTION
**Pull request by kscheirer**
Taken from https://redoc.ly/docs/cli/configuration/reference-docs/, just filtered to only CE options.

### CODE REVIEW

**Comment by adamaltman** [comment]
Thanks @kscheirer

**Review by RomanHotsiy — CHANGES_REQUESTED** [review]
Hey @kscheirer!

Looks good!

Could you please clean up those `# CE` comments?

**Comment by kscheirer** [comment]
thanks @RomanHotsiy, updated this PR

**Comment by aminaev-idt** [comment]
> Taken from https://redoc.ly/docs/cli/configuration/reference-docs/, just filtered to only CE options.

Hello. This config is not working or I'm wrong ? 
I run it in docker. Add -e REDOC_OPTIONS="theme.colors.primary.main='#FFA500'"
no result. 
@kscheirer did you test it ?

**Review by Gabbe-Menu — APPROVED** [review]

**Comment by kscheirer** [comment]
I tested the options I was using, they all worked ok. But I was not using docker or the `-e` syntax.

**Review by RomanHotsiy — APPROVED** [review]

**Comment by RomanHotsiy** [comment]
Thanks @kscheirer!

**Comment by swapnilogale** [comment]
Fixes https://github.com/Redocly/redoc/issues/523

**Comment by siarhei-kurhuzenkau-idf** [comment]
@kscheirer , @RomanHotsiy 

Hello. Could you please provide examples of using the <theme> options for docker with the -e syntax?

**Pull request merged**
