### PR TITLE
fix: use h2/h3 for headings instead of h1/h2 for better seo

### PR DESCRIPTION
**Pull request by maxkrumpe**
## What/Why/How?
Changed headings from h1/h2 to h2/h3 for content items for a better seo behavior.

Because of multiple h1 tags Google will list the pages more bad than with a better structured layout.

## Reference
See https://github.com/Redocly/redoc/issues/2513

## Tests
All tests were successfully run (unit tests). 
We do not consider issues because only the headings were changed. 
Only the look an feel (smaller headings for tags) is a bit different (see screenshot).

## Screenshots (optional)
image

## Check yourself

- [x] Code is linted
- [x] Tested
- [x] All new/updated code is covered with tests

### CODE REVIEW

**Comment by maxkrumpe** [comment]
Hey @RomanHotsiy, would you like to spend some time to review this PR?
I am not sure if I forgot something for this PR :)

**Review by AlexVarchuk — CHANGES_REQUESTED** [review]
Please update e2e tests. A couple of them failed in menu.e2e.ts

**Comment by maxkrumpe** [comment]
> Please update e2e tests. A couple of them failed in menu.e2e.ts

Thanks for the notifications. 
Now the tests are running again :)

**Review by AlexVarchuk — APPROVED** [review]

**Comment by AlexVarchuk** [comment]
@maxkrumpe please merge your PR when you are ready.

**Comment by maxkrumpe** [comment]
> @maxkrumpe please merge your PR when you are ready.

@AlexVarchuk I don't have write access to the repository so unfortunately I cannot merge the PR.
image

Do you have write access to it to merge the PR?

**Comment by AlexVarchuk** [comment]
@maxkrumpe Done. Thank you very much for your contribution. 🙌

**Pull request merged**
