### PR TITLE
Supports React 18

### PR DESCRIPTION
**Pull request by Mokto**
## What/Why/How?

npm install crashes right if using version 18

### CODE REVIEW

**Comment by AlexVarchuk** [comment]
@Mokto Hi! Thank you for your contribution.
Does it work with `React.StrictMode`? Details you can check [here](https://github.com/Redocly/redoc/issues/2023)

**Comment by Mokto** [comment]
Works perfectly with & without it.

In my case at least. Using the `RedocStandalone` component.

**Comment by Mokto** [comment]
Note: i used `npm install --force` to force react 18.

**Comment by AlexVarchuk** [comment]
We appreciate your contribution, but this PR is not added full support for React 18.
We created [the issue](https://github.com/Redocly/redoc/issues/2164) for that.

**Pull request closed without merging**
